/**
 * Build the AdGuard CLI blocker module into one directory: the module process bundled into one
 * file, its manifest generated from the module definition, and the setup action with the scripts it
 * runs: the fetch that installs a verified CLI release and the seed that activates it once.
 *
 * Its output is the repository's `adguard-cli/` directory, so a workflow plugs the CLI in with
 * `uses: <owner>/filters-agent/adguard-cli@<ref>`.
 *
 * Usage: node --import tsx scripts/build-adguard-cli-module.ts <out-dir>
 *
 * `pnpm run build:adguard-cli` runs it with `adguard-cli` as the output directory.
 */
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { ADGUARD_CLI_MODULE } from '../src/adguard-cli/adguard-cli-module';
import {
    ADGUARD_CLI_HOME_ARCHIVE_ENV,
    ADGUARD_LICENSE_KEY_ENV,
} from '../src/adguard-cli/adguard-cli-proxy';
import type { BlockerModuleManifest } from '../src/proxy-blocker/blocker-module-manifest';

/**
 * Node release the module process runs on: the action image's own.
 */
const NODE_TARGET = 'node24';

const outDir = process.argv[2];
if (!outDir) {
    console.error('Usage: build-adguard-cli-module.ts <out-dir>');
    process.exit(2);
}
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
mkdirSync(outDir, { recursive: true });

await build({
    entryPoints: [join(repoRoot, 'src/adguard-cli/adguard-cli-module-main.ts')],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: NODE_TARGET,
    outfile: join(outDir, 'module.mjs'),
    banner: {
        js: '// Generated by scripts/build-adguard-cli-module.ts from the filters-agent sources. Do not edit.',
    },
    logLevel: 'warning',
});

// The release path is the module's own default (bin/adguard-cli beside module.mjs), so the
// manifest requires only the licence the workflow must supply. The seeded HOME the setup action
// restores is optional: without it the module activates the licence itself.
const manifest: BlockerModuleManifest = {
    executor: ADGUARD_CLI_MODULE.executor,
    selectionGuidance: ADGUARD_CLI_MODULE.selectionGuidance,
    command: ['node', './module.mjs'],
    env: [ADGUARD_LICENSE_KEY_ENV],
    optionalEnv: [ADGUARD_CLI_HOME_ARCHIVE_ENV],
};
writeFileSync(join(outDir, 'blocker-module.json'), `${JSON.stringify(manifest, null, 4)}\n`);

copyFileSync(join(repoRoot, 'modules/adguard-cli/action.yml'), join(outDir, 'action.yml'));
for (const script of [
    'fetch-adguard-cli.mjs',
    'seed-adguard-cli-home.sh',
    'pack-adguard-cli-home.sh',
]) {
    copyFileSync(join(repoRoot, 'scripts', script), join(outDir, script));
}
console.log(`Built the AdGuard CLI module into ${outDir}`);
