// Generated by scripts/build-adguard-cli-module.ts from the filters-agent sources. Do not edit.

// src/adguard-cli/adguard-cli-module-main.ts
import { realpathSync } from "node:fs";
import { dirname, join as join5 } from "node:path";
import { fileURLToPath } from "node:url";

// src/blocker-contract/blocker-contract.ts
var BLOCKER_CONTRACT_VERSION = 1;
var BLOCKER_WORKSPACE_ENV = "FILTERS_AGENT_BLOCKER_WORKSPACE";
var BlockerKind = {
  Proxy: "proxy"
};
var PageEvidenceFormat = {
  /**
   * Element-hiding markers `adguard<list>;<rule>` on hidden elements and content scripts that
   * list the script rules they run, served from {@link PageEvidence.contentScriptHost}.
   */
  AdguardMarkers: "adguard_markers"
};
var BlockerEventKind = {
  /**
   * A network request a rule decided.
   */
  Request: "request",
  /**
   * An element the blocker removed from served HTML.
   */
  HtmlElementRemoved: "html_element_removed"
};

// src/blocker-contract/serve-blocker.ts
import { createInterface } from "node:readline";

// ../../../../../../../Volumes/dev/adguard-filters-agent/node_modules/.pnpm/valibot@1.4.1_typescript@5.9.3/node_modules/valibot/dist/index.mjs
var store$4;
var DEFAULT_CONFIG = {
  lang: void 0,
  message: void 0,
  abortEarly: void 0,
  abortPipeEarly: void 0
};
// @__NO_SIDE_EFFECTS__
function getGlobalConfig(config$1) {
  if (!config$1 && !store$4) return DEFAULT_CONFIG;
  return {
    lang: config$1?.lang ?? store$4?.lang,
    message: config$1?.message,
    abortEarly: config$1?.abortEarly ?? store$4?.abortEarly,
    abortPipeEarly: config$1?.abortPipeEarly ?? store$4?.abortPipeEarly
  };
}
var store$3;
// @__NO_SIDE_EFFECTS__
function getGlobalMessage(lang) {
  return store$3?.get(lang);
}
var store$2;
// @__NO_SIDE_EFFECTS__
function getSchemaMessage(lang) {
  return store$2?.get(lang);
}
var store$1;
// @__NO_SIDE_EFFECTS__
function getSpecificMessage(reference, lang) {
  return store$1?.get(reference)?.get(lang);
}
// @__NO_SIDE_EFFECTS__
function _stringify(input) {
  const type = typeof input;
  if (type === "string") return `"${input}"`;
  if (type === "number" || type === "bigint" || type === "boolean") return `${input}`;
  if (type === "object" || type === "function") return (input && Object.getPrototypeOf(input)?.constructor?.name) ?? "null";
  return type;
}
function _addIssue(context, label, dataset, config$1, other) {
  const input = other && "input" in other ? other.input : dataset.value;
  const expected = other?.expected ?? context.expects ?? null;
  const received = other?.received ?? /* @__PURE__ */ _stringify(input);
  const issue = {
    kind: context.kind,
    type: context.type,
    input,
    expected,
    received,
    message: `Invalid ${label}: ${expected ? `Expected ${expected} but r` : "R"}eceived ${received}`,
    requirement: context.requirement,
    path: other?.path,
    issues: other?.issues,
    lang: config$1.lang,
    abortEarly: config$1.abortEarly,
    abortPipeEarly: config$1.abortPipeEarly
  };
  const isSchema = context.kind === "schema";
  const message$1 = other?.message ?? context.message ?? /* @__PURE__ */ getSpecificMessage(context.reference, issue.lang) ?? (isSchema ? /* @__PURE__ */ getSchemaMessage(issue.lang) : null) ?? config$1.message ?? /* @__PURE__ */ getGlobalMessage(issue.lang);
  if (message$1 !== void 0) issue.message = typeof message$1 === "function" ? message$1(issue) : message$1;
  if (isSchema) dataset.typed = false;
  if (dataset.issues) dataset.issues.push(issue);
  else dataset.issues = [issue];
}
var _standardCache = /* @__PURE__ */ new WeakMap();
// @__NO_SIDE_EFFECTS__
function _getStandardProps(context) {
  let cached = _standardCache.get(context);
  if (!cached) {
    cached = {
      version: 1,
      vendor: "valibot",
      validate(value$1) {
        return context["~run"]({ value: value$1 }, /* @__PURE__ */ getGlobalConfig());
      }
    };
    _standardCache.set(context, cached);
  }
  return cached;
}
// @__NO_SIDE_EFFECTS__
function _joinExpects(values$1, separator) {
  const list = [...new Set(values$1)];
  if (list.length > 1) return `(${list.join(` ${separator} `)})`;
  return list[0] ?? "never";
}
var BASE64_REGEX = /^(?:[\da-z+/]{4})*(?:[\da-z+/]{2}==|[\da-z+/]{3}=)?$/iu;
var EMOJI_REGEX = new RegExp("^(?:[\\u{1F1E6}-\\u{1F1FF}]{2}|\\u{1F3F4}[\\u{E0061}-\\u{E007A}]{2}[\\u{E0030}-\\u{E0039}\\u{E0061}-\\u{E007A}]{1,3}\\u{E007F}|(?:\\p{Emoji}\\uFE0F\\u20E3?|\\p{Emoji_Modifier_Base}\\p{Emoji_Modifier}?|(?![\\p{Emoji_Modifier_Base}\\u{1F1E6}-\\u{1F1FF}])\\p{Emoji_Presentation})(?:\\u200D(?:\\p{Emoji}\\uFE0F\\u20E3?|\\p{Emoji_Modifier_Base}\\p{Emoji_Modifier}?|(?![\\p{Emoji_Modifier_Base}\\u{1F1E6}-\\u{1F1FF}])\\p{Emoji_Presentation}))*)+$", "u");
var HEXADECIMAL_REGEX = /^(?:0[hx])?[\da-fA-F]+$/u;
// @__NO_SIDE_EFFECTS__
function base64(message$1) {
  return {
    kind: "validation",
    type: "base64",
    reference: base64,
    async: false,
    expects: null,
    requirement: BASE64_REGEX,
    message: message$1,
    "~run"(dataset, config$1) {
      if (dataset.typed && !this.requirement.test(dataset.value)) _addIssue(this, "Base64", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function hexadecimal(message$1) {
  return {
    kind: "validation",
    type: "hexadecimal",
    reference: hexadecimal,
    async: false,
    expects: null,
    requirement: HEXADECIMAL_REGEX,
    message: message$1,
    "~run"(dataset, config$1) {
      if (dataset.typed && !this.requirement.test(dataset.value)) _addIssue(this, "hexadecimal", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function integer(message$1) {
  return {
    kind: "validation",
    type: "integer",
    reference: integer,
    async: false,
    expects: null,
    requirement: Number.isInteger,
    message: message$1,
    "~run"(dataset, config$1) {
      if (dataset.typed && !this.requirement(dataset.value)) _addIssue(this, "integer", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function length(requirement, message$1) {
  return {
    kind: "validation",
    type: "length",
    reference: length,
    async: false,
    expects: `${requirement}`,
    requirement,
    message: message$1,
    "~run"(dataset, config$1) {
      if (dataset.typed && dataset.value.length !== this.requirement) _addIssue(this, "length", dataset, config$1, { received: `${dataset.value.length}` });
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function minValue(requirement, message$1) {
  return {
    kind: "validation",
    type: "min_value",
    reference: minValue,
    async: false,
    expects: `>=${requirement instanceof Date ? requirement.toJSON() : /* @__PURE__ */ _stringify(requirement)}`,
    requirement,
    message: message$1,
    "~run"(dataset, config$1) {
      if (dataset.typed && !(dataset.value >= this.requirement)) _addIssue(this, "value", dataset, config$1, { received: dataset.value instanceof Date ? dataset.value.toJSON() : /* @__PURE__ */ _stringify(dataset.value) });
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function nonEmpty(message$1) {
  return {
    kind: "validation",
    type: "non_empty",
    reference: nonEmpty,
    async: false,
    expects: "!0",
    message: message$1,
    "~run"(dataset, config$1) {
      if (dataset.typed && dataset.value.length === 0) _addIssue(this, "length", dataset, config$1, { received: "0" });
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function url(message$1) {
  return {
    kind: "validation",
    type: "url",
    reference: url,
    async: false,
    expects: null,
    requirement(input) {
      try {
        new URL(input);
        return true;
      } catch {
        return false;
      }
    },
    message: message$1,
    "~run"(dataset, config$1) {
      if (dataset.typed && !this.requirement(dataset.value)) _addIssue(this, "URL", dataset, config$1);
      return dataset;
    }
  };
}
var ABORT_EARLY_CONFIG = { abortEarly: true };
// @__NO_SIDE_EFFECTS__
function getFallback(schema, dataset, config$1) {
  return typeof schema.fallback === "function" ? schema.fallback(dataset, config$1) : schema.fallback;
}
// @__NO_SIDE_EFFECTS__
function getDefault(schema, dataset, config$1) {
  return typeof schema.default === "function" ? schema.default(dataset, config$1) : schema.default;
}
// @__NO_SIDE_EFFECTS__
function array(item, message$1) {
  return {
    kind: "schema",
    type: "array",
    reference: array,
    expects: "Array",
    async: false,
    item,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      const input = dataset.value;
      if (Array.isArray(input)) {
        dataset.typed = true;
        dataset.value = [];
        for (let key = 0; key < input.length; key++) {
          const value$1 = input[key];
          const itemDataset = this.item["~run"]({ value: value$1 }, config$1);
          if (itemDataset.issues) {
            const pathItem = {
              type: "array",
              origin: "value",
              input,
              key,
              value: value$1
            };
            for (const issue of itemDataset.issues) {
              if (issue.path) issue.path.unshift(pathItem);
              else issue.path = [pathItem];
              dataset.issues?.push(issue);
            }
            if (!dataset.issues) dataset.issues = itemDataset.issues;
            if (config$1.abortEarly) {
              dataset.typed = false;
              break;
            }
          }
          if (!itemDataset.typed) dataset.typed = false;
          dataset.value.push(itemDataset.value);
        }
      } else _addIssue(this, "type", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function boolean(message$1) {
  return {
    kind: "schema",
    type: "boolean",
    reference: boolean,
    expects: "boolean",
    async: false,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      if (typeof dataset.value === "boolean") dataset.typed = true;
      else _addIssue(this, "type", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function literal(literal_, message$1) {
  return {
    kind: "schema",
    type: "literal",
    reference: literal,
    expects: /* @__PURE__ */ _stringify(literal_),
    async: false,
    literal: literal_,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      if (dataset.value === this.literal) dataset.typed = true;
      else _addIssue(this, "type", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function nullable(wrapped, default_) {
  return {
    kind: "schema",
    type: "nullable",
    reference: nullable,
    expects: `(${wrapped.expects} | null)`,
    async: false,
    wrapped,
    default: default_,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      if (dataset.value === null) {
        if (this.default !== void 0) dataset.value = /* @__PURE__ */ getDefault(this, dataset, config$1);
        if (dataset.value === null) {
          dataset.typed = true;
          return dataset;
        }
      }
      return this.wrapped["~run"](dataset, config$1);
    }
  };
}
// @__NO_SIDE_EFFECTS__
function number(message$1) {
  return {
    kind: "schema",
    type: "number",
    reference: number,
    expects: "number",
    async: false,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      if (typeof dataset.value === "number" && !isNaN(dataset.value)) dataset.typed = true;
      else _addIssue(this, "type", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function object(entries$1, message$1) {
  return {
    kind: "schema",
    type: "object",
    reference: object,
    expects: "Object",
    async: false,
    entries: entries$1,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      const input = dataset.value;
      if (input && typeof input === "object") {
        dataset.typed = true;
        dataset.value = {};
        for (const key in this.entries) {
          const valueSchema = this.entries[key];
          if (key in input || (valueSchema.type === "exact_optional" || valueSchema.type === "optional" || valueSchema.type === "nullish") && valueSchema.default !== void 0) {
            const value$1 = key in input ? input[key] : /* @__PURE__ */ getDefault(valueSchema);
            const valueDataset = valueSchema["~run"]({ value: value$1 }, config$1);
            if (valueDataset.issues) {
              const pathItem = {
                type: "object",
                origin: "value",
                input,
                key,
                value: value$1
              };
              for (const issue of valueDataset.issues) {
                if (issue.path) issue.path.unshift(pathItem);
                else issue.path = [pathItem];
                dataset.issues?.push(issue);
              }
              if (!dataset.issues) dataset.issues = valueDataset.issues;
              if (config$1.abortEarly) {
                dataset.typed = false;
                break;
              }
            }
            if (!valueDataset.typed) dataset.typed = false;
            dataset.value[key] = valueDataset.value;
          } else if (valueSchema.fallback !== void 0) dataset.value[key] = /* @__PURE__ */ getFallback(valueSchema);
          else if (valueSchema.type !== "exact_optional" && valueSchema.type !== "optional" && valueSchema.type !== "nullish") {
            _addIssue(this, "key", dataset, config$1, {
              input: void 0,
              expected: `"${key}"`,
              path: [{
                type: "object",
                origin: "key",
                input,
                key,
                value: input[key]
              }]
            });
            if (config$1.abortEarly) break;
          }
        }
      } else _addIssue(this, "type", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function picklist(options, message$1) {
  return {
    kind: "schema",
    type: "picklist",
    reference: picklist,
    expects: /* @__PURE__ */ _joinExpects(options.map(_stringify), "|"),
    async: false,
    options,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      if (this.options.includes(dataset.value)) dataset.typed = true;
      else _addIssue(this, "type", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function string(message$1) {
  return {
    kind: "schema",
    type: "string",
    reference: string,
    expects: "string",
    async: false,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      if (typeof dataset.value === "string") dataset.typed = true;
      else _addIssue(this, "type", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function _subIssues(datasets) {
  let issues;
  if (datasets) for (const dataset of datasets) if (issues) for (const issue of dataset.issues) issues.push(issue);
  else issues = dataset.issues;
  return issues;
}
// @__NO_SIDE_EFFECTS__
function union(options, message$1) {
  return {
    kind: "schema",
    type: "union",
    reference: union,
    expects: /* @__PURE__ */ _joinExpects(options.map((option) => option.expects), "|"),
    async: false,
    options,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      let validDataset;
      let typedDatasets;
      let untypedDatasets;
      for (const schema of this.options) {
        const optionDataset = schema["~run"]({ value: dataset.value }, config$1);
        if (optionDataset.typed) if (optionDataset.issues) if (typedDatasets) typedDatasets.push(optionDataset);
        else typedDatasets = [optionDataset];
        else {
          validDataset = optionDataset;
          break;
        }
        else if (untypedDatasets) untypedDatasets.push(optionDataset);
        else untypedDatasets = [optionDataset];
      }
      if (validDataset) return validDataset;
      if (typedDatasets) {
        if (typedDatasets.length === 1) return typedDatasets[0];
        _addIssue(this, "type", dataset, config$1, { issues: /* @__PURE__ */ _subIssues(typedDatasets) });
        dataset.typed = true;
      } else if (untypedDatasets?.length === 1) return untypedDatasets[0];
      else _addIssue(this, "type", dataset, config$1, { issues: /* @__PURE__ */ _subIssues(untypedDatasets) });
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function unknown() {
  return {
    kind: "schema",
    type: "unknown",
    reference: unknown,
    expects: "unknown",
    async: false,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset) {
      dataset.typed = true;
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function variant(key, options, message$1) {
  return {
    kind: "schema",
    type: "variant",
    reference: variant,
    expects: "Object",
    async: false,
    key,
    options,
    message: message$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      const input = dataset.value;
      if (input && typeof input === "object") {
        let outputDataset;
        let maxDiscriminatorPriority = 0;
        let invalidDiscriminatorKey = this.key;
        let expectedDiscriminators = [];
        const parseOptions = (variant$1, allKeys) => {
          for (const schema of variant$1.options) {
            if (schema.type === "variant") parseOptions(schema, new Set(allKeys).add(schema.key));
            else {
              let keysAreValid = true;
              let currentPriority = 0;
              for (const currentKey of allKeys) {
                const discriminatorSchema = schema.entries[currentKey];
                if (currentKey in input ? discriminatorSchema["~run"]({
                  typed: false,
                  value: input[currentKey]
                }, ABORT_EARLY_CONFIG).issues : discriminatorSchema.type !== "exact_optional" && discriminatorSchema.type !== "optional" && discriminatorSchema.type !== "nullish") {
                  keysAreValid = false;
                  if (invalidDiscriminatorKey !== currentKey && (maxDiscriminatorPriority < currentPriority || maxDiscriminatorPriority === currentPriority && currentKey in input && !(invalidDiscriminatorKey in input))) {
                    maxDiscriminatorPriority = currentPriority;
                    invalidDiscriminatorKey = currentKey;
                    expectedDiscriminators = [];
                  }
                  if (invalidDiscriminatorKey === currentKey) expectedDiscriminators.push(schema.entries[currentKey].expects);
                  break;
                }
                currentPriority++;
              }
              if (keysAreValid) {
                const optionDataset = schema["~run"]({ value: input }, config$1);
                if (!outputDataset || !outputDataset.typed && optionDataset.typed) outputDataset = optionDataset;
              }
            }
            if (outputDataset && !outputDataset.issues) break;
          }
        };
        parseOptions(this, /* @__PURE__ */ new Set([this.key]));
        if (outputDataset) return outputDataset;
        _addIssue(this, "type", dataset, config$1, {
          input: input[invalidDiscriminatorKey],
          expected: /* @__PURE__ */ _joinExpects(expectedDiscriminators, "|"),
          path: [{
            type: "object",
            origin: "value",
            input,
            key: invalidDiscriminatorKey,
            value: input[invalidDiscriminatorKey]
          }]
        });
      } else _addIssue(this, "type", dataset, config$1);
      return dataset;
    }
  };
}
// @__NO_SIDE_EFFECTS__
function pipe(...pipe$1) {
  return {
    ...pipe$1[0],
    pipe: pipe$1,
    get "~standard"() {
      return /* @__PURE__ */ _getStandardProps(this);
    },
    "~run"(dataset, config$1) {
      for (const item of pipe$1) if (item.kind !== "metadata") {
        if (dataset.issues && (item.kind === "schema" || item.kind === "transformation")) {
          dataset.typed = false;
          break;
        }
        if (!dataset.issues || !config$1.abortEarly && !config$1.abortPipeEarly) dataset = item["~run"](dataset, config$1);
      }
      return dataset;
    }
  };
}

// src/blocker-contract/blocker-wire.ts
var BlockerMethod = {
  Describe: "describe",
  Start: "start",
  Apply: "apply",
  State: "state",
  Log: "log",
  Stop: "stop"
};
var RouteSchema = object({
  proxyUrl: pipe(string(), url()),
  certificateDerBase64: pipe(string(), base64())
});
var RunningSchema = object({
  route: RouteSchema,
  revision: pipe(number(), integer(), minValue(1))
});
var BlockerDescriptionSchema = object({
  contractVersion: pipe(number(), integer()),
  product: pipe(string(), nonEmpty()),
  version: nullable(string()),
  binarySha256: pipe(string(), hexadecimal(), length(64)),
  kind: picklist(Object.values(BlockerKind)),
  covers: string(),
  notReported: array(string()),
  pageEvidence: nullable(
    object({
      format: picklist(Object.values(PageEvidenceFormat)),
      contentScriptHost: pipe(string(), nonEmpty())
    })
  )
});
var BlockerRunningSchema = RunningSchema;
var BlockerAppliedSchema = object({
  ...RunningSchema.entries,
  restarted: boolean()
});
var BlockerStateSchema = object({
  running: boolean(),
  revision: pipe(number(), integer(), minValue(0)),
  port: nullable(pipe(number(), integer())),
  lists: array(
    object({
      id: pipe(number(), integer()),
      sha256: pipe(string(), hexadecimal(), length(64))
    })
  ),
  userRules: array(string())
});
var BlockerLogReadSchema = object({
  revision: pipe(number(), integer(), minValue(0)),
  cursor: string(),
  events: array(
    variant("kind", [
      object({
        kind: literal(BlockerEventKind.Request),
        url: string(),
        rule: string(),
        handshakeBlock: boolean()
      }),
      object({
        kind: literal(BlockerEventKind.HtmlElementRemoved),
        url: string(),
        element: string(),
        rule: string()
      })
    ])
  )
});
var BlockerStoppedSchema = object({
  licenceReleased: boolean()
});
var BlockerWireResponseSchema = union([
  object({ id: pipe(number(), integer()), result: unknown() }),
  object({ id: pipe(number(), integer()), error: object({ message: string() }) })
]);
var BLOCKER_RESULT_SCHEMAS = {
  [BlockerMethod.Describe]: BlockerDescriptionSchema,
  [BlockerMethod.Start]: BlockerRunningSchema,
  [BlockerMethod.Apply]: BlockerAppliedSchema,
  [BlockerMethod.State]: BlockerStateSchema,
  [BlockerMethod.Log]: BlockerLogReadSchema,
  [BlockerMethod.Stop]: BlockerStoppedSchema
};

// src/blocker-contract/serve-blocker.ts
async function dispatch(blocker, request) {
  switch (request.method) {
    case BlockerMethod.Describe:
      return await blocker.describe();
    case BlockerMethod.Start:
      return await blocker.start(request.params);
    case BlockerMethod.Apply:
      return await blocker.apply(request.params);
    case BlockerMethod.State:
      return await blocker.state();
    case BlockerMethod.Log:
      return await blocker.log(request.params);
    case BlockerMethod.Stop:
      return await blocker.stop();
  }
}
async function serveBlocker(blocker, input, output) {
  let queue = Promise.resolve();
  const lines = createInterface({ input });
  lines.on("line", (line) => {
    const request = JSON.parse(line);
    queue = queue.then(async () => {
      try {
        const result = await dispatch(blocker, request);
        output.write(`${JSON.stringify({ id: request.id, result })}
`);
      } catch (error) {
        console.error(error);
        const message = error instanceof Error ? error.message : String(error);
        output.write(`${JSON.stringify({ id: request.id, error: { message } })}
`);
      }
    });
  });
  await new Promise((resolve) => lines.once("close", resolve));
  await queue;
  await blocker.stop();
}

// src/adguard-cli/adguard-cli-blocker.ts
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join as join3 } from "node:path";
import { promisify } from "node:util";

// src/adguard-cli/adguard-cli-log.ts
import { open } from "node:fs/promises";
import { join } from "node:path";

// src/adguard-cli/adguard-cli-proxy-config.ts
var USER_RULES_FILENAME = "user.txt";
var CONFIG_FILENAME = "proxy.yaml";
var OUTPUT_LOG_FILENAME = "proxy-output.log";
var ACCESS_LOG_FILENAME = "access.log";
var INJECTIONS_HOST = "local.adguard.org";
function filterFilename(filterId) {
  return `filter-${filterId}.txt`;
}

// src/adguard-cli/adguard-cli-log.ts
var ACCESS_LOG_LINE = /^\S+ \S+ "[^"]*" \S+ \S+ (?<url>\S+) \S+ \d+ \S+ \S+ \d+ \S+ \S+ \d+b \d+ms -- ?(?<rule>.*)$/u;
var TLS_BLOCK_LINE = /^\S+ \S+ "[^"]*" TLS - (?<url>\S+) - - \S+ BLOCKED \d+ \S+ \S+ \d+b \d+ms -- (?<rule>.+)$/u;
var ELEMENT_REMOVED_LINE = /onHtmlElementRemoved: \[[^\]]*\] rule:(?<rule>.+?) url:(?<url>\S*) element name:(?<element>\S+)/u;
var LINE_BREAK = /\r?\n/u;
var LINE_FEED = 10;
var CURSOR_SEPARATOR = ":";
function parseAccessLogLine(line) {
  const request = ACCESS_LOG_LINE.exec(line)?.groups;
  if (request !== void 0) {
    const rule = request.rule.trimEnd();
    return rule.length === 0 ? void 0 : { kind: BlockerEventKind.Request, url: request.url, rule, handshakeBlock: false };
  }
  const handshake = TLS_BLOCK_LINE.exec(line)?.groups;
  return handshake === void 0 ? void 0 : {
    kind: BlockerEventKind.Request,
    url: handshake.url,
    rule: handshake.rule.trimEnd(),
    handshakeBlock: true
  };
}
function parseOutputLogLine(line) {
  const match = ELEMENT_REMOVED_LINE.exec(line)?.groups;
  return match === void 0 ? void 0 : {
    kind: BlockerEventKind.HtmlElementRemoved,
    url: match.url,
    element: match.element,
    rule: match.rule
  };
}
async function completeLinesSince(path, offset) {
  let handle;
  try {
    handle = await open(path, "r");
  } catch (error) {
    if (error.code === "ENOENT") {
      return { lines: [], offset };
    }
    throw error;
  }
  try {
    const size = (await handle.stat()).size;
    if (size <= offset) {
      return { lines: [], offset };
    }
    const bytes = Buffer.alloc(size - offset);
    await handle.read(bytes, 0, bytes.length, offset);
    const end = bytes.lastIndexOf(LINE_FEED) + 1;
    return {
      lines: bytes.subarray(0, end).toString("utf8").split(LINE_BREAK).filter(Boolean),
      offset: offset + end
    };
  } finally {
    await handle.close();
  }
}
async function logSize(path) {
  let handle;
  try {
    handle = await open(path, "r");
  } catch (error) {
    if (error.code === "ENOENT") {
      return 0;
    }
    throw error;
  }
  try {
    return (await handle.stat()).size;
  } finally {
    await handle.close();
  }
}
async function readAdguardCliLog(workspaceDir, cursor, revision) {
  const accessLogPath = join(workspaceDir, ACCESS_LOG_FILENAME);
  const outputLogPath = join(workspaceDir, OUTPUT_LOG_FILENAME);
  if (cursor === null) {
    const now = [await logSize(accessLogPath), await logSize(outputLogPath)];
    return { revision, cursor: now.join(CURSOR_SEPARATOR), events: [] };
  }
  const [accessOffset, outputOffset] = cursor.split(CURSOR_SEPARATOR).map(Number);
  const access = await completeLinesSince(accessLogPath, accessOffset);
  const output = await completeLinesSince(outputLogPath, outputOffset);
  const events = [
    ...access.lines.map(parseAccessLogLine),
    ...output.lines.map(parseOutputLogLine)
  ].filter((event) => event !== void 0);
  return {
    revision,
    cursor: [access.offset, output.offset].join(CURSOR_SEPARATOR),
    events
  };
}

// src/adguard-cli/proxy-host.ts
import { spawn } from "node:child_process";
import { mkdir, open as open2, writeFile, chmod } from "node:fs/promises";
import { connect, createServer } from "node:net";
import { join as join2 } from "node:path";
var READINESS_TIMEOUT_MS = 6e4;
var READINESS_POLL_MS = 250;
var TERMINATE_GRACE_MS = 1e4;
var ProxyHostState = {
  New: "new",
  Prepared: "prepared",
  Running: "running",
  Stopped: "stopped",
  Failed: "failed"
};
var ProxyFailureCode = {
  WorkspaceUnwritable: "workspace_unwritable",
  SpawnFailed: "spawn_failed",
  ReadinessTimeout: "readiness_timeout",
  ProcessExited: "process_exited",
  DataDirectoryUnknown: "data_directory_unknown",
  ActivationFailed: "activation_failed",
  CertificateUnavailable: "certificate_unavailable"
};
var ProxyHostError = class extends Error {
  /**
   * Create one path-free proxy failure.
   *
   * @param code - Stable public failure classification.
   * @param cause - Underlying error, kept for the log.
   */
  constructor(code, cause) {
    super(`Filtering proxy failed: ${code}.`, { cause });
    this.code = code;
    this.name = "ProxyHostError";
  }
  code;
};
var liveProxies = /* @__PURE__ */ new Set();
var orphanGuardInstalled = false;
function registerOrphanGuard(child) {
  liveProxies.add(child);
  child.once("exit", () => liveProxies.delete(child));
  if (orphanGuardInstalled) {
    return;
  }
  orphanGuardInstalled = true;
  const killAll = () => {
    for (const proxy of liveProxies) {
      proxy.kill("SIGKILL");
    }
    liveProxies.clear();
  };
  process.once("exit", killAll);
  for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) {
    process.once(signal, () => {
      killAll();
      process.kill(process.pid, signal);
    });
  }
}
async function reserveLoopbackPort() {
  return await new Promise((resolve, reject) => {
    const server = createServer();
    server.once("error", reject);
    server.listen({ host: "127.0.0.1", port: 0, exclusive: true }, () => {
      const address = server.address();
      if (address === null || typeof address === "string") {
        server.close(() => reject(new Error("port_reservation_failed")));
        return;
      }
      const { port } = address;
      server.close(() => resolve(port));
    });
  });
}
async function probeLoopbackPort(port) {
  return await new Promise((resolve) => {
    const socket = connect({ host: "127.0.0.1", port });
    const settle = (value) => {
      socket.destroy();
      resolve(value);
    };
    socket.setTimeout(2e3);
    socket.once("connect", () => settle(true));
    socket.once("timeout", () => settle(false));
    socket.once("error", () => settle(false));
  });
}
function describeError(error) {
  if (!(error instanceof Error)) {
    return { error: String(error) };
  }
  return {
    error: error.message,
    stack: error.stack,
    ...error.cause === void 0 ? {} : { cause: describeError(error.cause) }
  };
}
function createProxyHost(input, engine) {
  const reservePort = input.reservePort ?? reserveLoopbackPort;
  const spawnProcess = input.spawnProcess ?? spawn;
  const probePort = input.probePort ?? probeLoopbackPort;
  const log = (fields, message) => {
    input.logger?.info(fields, `${engine.name} ${message}`);
  };
  let state = ProxyHostState.New;
  let failureCode = null;
  let child = null;
  let childExited = false;
  let port = null;
  let userRules = [];
  let replacedFilterId = null;
  let enabledFilterIds = null;
  let authority = null;
  let released = false;
  let executed = null;
  const userRulesPath = join2(input.workspaceDir, USER_RULES_FILENAME);
  const outputLogPath = join2(input.workspaceDir, OUTPUT_LOG_FILENAME);
  const activeFilterIds = () => {
    return input.filterLists.map((list) => list.filterId).filter((filterId) => enabledFilterIds === null || enabledFilterIds.has(filterId));
  };
  const fail = (code) => {
    state = ProxyHostState.Failed;
    failureCode ??= code;
    return new ProxyHostError(code);
  };
  const writeFilterList = async (list) => {
    await writeFile(
      join2(input.workspaceDir, filterFilename(list.filterId)),
      list.content.endsWith("\n") ? list.content : `${list.content}
`,
      { mode: 384 }
    );
  };
  const writeUserRules = async () => {
    const body = ["! Agent-authored rules", ...userRules].join("\n");
    await writeFile(userRulesPath, `${body}
`, { mode: 384 });
  };
  const release = async () => {
    if (released) {
      return;
    }
    released = true;
    await engine.release();
  };
  const launch = async () => {
    if (authority === null) {
      throw new Error("The proxy host was not prepared.");
    }
    const chosenPort = await reservePort();
    const filterFilenames = [
      ...activeFilterIds().map((filterId) => filterFilename(filterId)),
      USER_RULES_FILENAME
    ];
    await engine.writeConfiguration(chosenPort, filterFilenames);
    const command = engine.command();
    const output = await open2(outputLogPath, "a", 384);
    let spawned;
    try {
      await output.write(
        `--- ${(/* @__PURE__ */ new Date()).toISOString()} starting ${engine.name} on port ${chosenPort} with filters ${activeFilterIds().join(",")} and ${userRules.length} user rules
`
      );
      spawned = spawnProcess(input.binaryPath, [...command.args], {
        cwd: command.cwd ?? input.workspaceDir,
        env: command.env,
        stdio: ["ignore", output.fd, output.fd]
      });
    } catch (error) {
      log(describeError(error), "spawn failed");
      throw fail(ProxyFailureCode.SpawnFailed);
    } finally {
      await output.close();
    }
    childExited = false;
    spawned.once("exit", (code, signal) => {
      childExited = true;
      log({ pid: spawned.pid ?? null, code, signal }, "process exited");
    });
    child = spawned;
    port = chosenPort;
    executed = { filterIds: activeFilterIds(), userRules: [...userRules] };
    registerOrphanGuard(spawned);
    const startedAt = Date.now();
    log(
      {
        port: chosenPort,
        filterIds: activeFilterIds(),
        preparedFilterIds: input.filterLists.map((list) => list.filterId),
        userRuleCount: userRules.length,
        pid: spawned.pid ?? null
      },
      "spawned, waiting for readiness"
    );
    const deadline = Date.now() + READINESS_TIMEOUT_MS;
    for (; ; ) {
      if (childExited) {
        throw fail(ProxyFailureCode.ProcessExited);
      }
      if (await probePort(chosenPort)) {
        break;
      }
      if (Date.now() > deadline) {
        throw fail(ProxyFailureCode.ReadinessTimeout);
      }
      await new Promise((resolve) => setTimeout(resolve, READINESS_POLL_MS));
    }
    state = ProxyHostState.Running;
    log({ port: chosenPort, readyMs: Date.now() - startedAt }, "ready");
    return { proxyUrl: `http://127.0.0.1:${chosenPort}`, port: chosenPort, ...authority };
  };
  const terminate = async () => {
    const running = child;
    child = null;
    port = null;
    executed = null;
    if (!running || childExited) {
      return;
    }
    await new Promise((resolve) => {
      const killTimer = setTimeout(() => running.kill("SIGKILL"), TERMINATE_GRACE_MS);
      running.once("exit", () => {
        clearTimeout(killTimer);
        resolve();
      });
      running.kill("SIGTERM");
    });
  };
  return {
    async prepare() {
      try {
        await mkdir(input.workspaceDir, { recursive: true, mode: 448 });
        await chmod(input.workspaceDir, 448);
        for (const list of input.filterLists) {
          await writeFilterList(list);
        }
        await writeUserRules();
      } catch (error) {
        log(describeError(error), "workspace preparation failed");
        throw fail(ProxyFailureCode.WorkspaceUnwritable);
      }
      try {
        authority = await engine.prepare();
      } catch (error) {
        log(describeError(error), "engine preparation failed");
        await release();
        throw error instanceof ProxyHostError ? fail(error.code) : fail(ProxyFailureCode.WorkspaceUnwritable);
      }
      state = ProxyHostState.Prepared;
    },
    async start() {
      return await launch();
    },
    async setUserRules(rules) {
      log({ ruleCount: rules.length }, "restarting for new user rules");
      userRules = [...rules];
      await writeUserRules();
      await terminate();
      return await launch();
    },
    async setFilterReplacement(replacement) {
      log(
        { replacedFilterId: replacement?.filterId ?? null },
        "restarting for a replaced filter list"
      );
      if (replacedFilterId !== null && replacedFilterId !== replacement?.filterId) {
        await writeFilterList(
          input.filterLists.find((list) => list.filterId === replacedFilterId)
        );
      }
      if (replacement !== null) {
        if (!input.filterLists.some((list) => list.filterId === replacement.filterId)) {
          throw new Error("The replaced filter list is not one this proxy prepared.");
        }
        await writeFilterList(replacement);
      }
      replacedFilterId = replacement?.filterId ?? null;
      await terminate();
      return await launch();
    },
    async setEnabledFilters(filterIds) {
      const desired = filterIds === null ? null : new Set(filterIds);
      const unchanged = desired === null ? enabledFilterIds === null : enabledFilterIds !== null && desired.size === enabledFilterIds.size && [...desired].every((filterId) => enabledFilterIds.has(filterId));
      if (unchanged) {
        return null;
      }
      enabledFilterIds = desired;
      if (child === null) {
        return null;
      }
      log(
        { filterIds: activeFilterIds(), userRuleCount: userRules.length },
        "restarting for new enabled filter set"
      );
      await terminate();
      return await launch();
    },
    async stop() {
      await terminate();
      await release();
      if (state !== ProxyHostState.Failed) {
        state = ProxyHostState.Stopped;
      }
    },
    snapshot() {
      return {
        state,
        port,
        filterIds: input.filterLists.map((list) => list.filterId),
        userRuleCount: userRules.length,
        executedFilterIds: executed?.filterIds ?? null,
        executedUserRules: executed?.userRules ?? null,
        failureCode
      };
    }
  };
}

// src/adguard-cli/adguard-cli-blocker.ts
var ADGUARD_CLI_PRODUCT_LABEL = "AdGuard CLI";
var COVERS = "Every request the proxy filtered and every script it injected since this browser session started, on any page (its logs have no page boundary); element hiding as the frames of the current page show it at the moment of the read.";
var NOT_REPORTED = [
  "Network rules other than the one that decided a request: document-level exceptions ($document, $elemhide, $generichide, $specifichide, $jsinject, $content) and rules that modify a request or response ($csp, $permissions, $removeparam, $removeheader, $cookie, $replace, $referrerpolicy, $hls, $jsonprune, $xmlprune, $urltransform). The proxy counts them on the request but never logs their text.",
  "Hiding by extended CSS (#?#) rules and by CSS rules that set their own content: the proxy marks neither on the element it hides."
];
var VERSION_LINE = /^AdGuard CLI v(\S+)/mu;
var VERSION_PROBE_TIMEOUT_MS = 3e4;
var execFileAsync = promisify(execFile);
async function probeVersion(binaryPath, logger) {
  const home = await mkdtemp(join3(tmpdir(), "agcli-version-"));
  try {
    const { stdout } = await execFileAsync(binaryPath, ["--version"], {
      env: { HOME: home, PATH: process.env["PATH"], LANG: "en_US.UTF-8" },
      timeout: VERSION_PROBE_TIMEOUT_MS
    });
    return VERSION_LINE.exec(stdout)?.[1] ?? null;
  } catch (error) {
    logger?.info(
      { error: error instanceof Error ? error.message : String(error) },
      "adguard cli version probe failed"
    );
    return null;
  } finally {
    await rm(home, { recursive: true, force: true });
  }
}
function sameReplacement(left, right) {
  return left === null || right === null ? left === right : left.id === right.id && left.content === right.content;
}
function createAdguardCliBlocker(input) {
  let proxy = null;
  let route = null;
  let revision = 0;
  let replacement = null;
  const requireProxy = (operation) => {
    if (proxy === null) {
      throw new Error(`The AdGuard CLI blocker answered ${operation} before it was started.`);
    }
    return proxy;
  };
  const running = (next) => {
    route = next;
    revision += 1;
    return {
      route: { proxyUrl: next.proxyUrl, certificateDerBase64: next.certificateDerBase64 },
      revision
    };
  };
  const applyRequest = async (request) => {
    const host = requireProxy("apply");
    const current = host.snapshot().executedUserRules ?? [];
    let restarted = false;
    const relisted = await host.setEnabledFilters(request.enabledListIds);
    if (relisted !== null) {
      running(relisted);
      restarted = true;
    }
    if (!sameReplacement(replacement, request.listReplacement)) {
      running(
        await host.setFilterReplacement(
          request.listReplacement === null ? null : {
            filterId: request.listReplacement.id,
            content: request.listReplacement.content
          }
        )
      );
      replacement = request.listReplacement;
      restarted = true;
    }
    const sameRules = current.length === request.userRules.length && current.every((rule, index) => rule === request.userRules[index]);
    if (!sameRules) {
      running(await host.setUserRules(request.userRules));
      restarted = true;
    }
    return {
      route: {
        proxyUrl: route.proxyUrl,
        certificateDerBase64: route.certificateDerBase64
      },
      revision,
      restarted
    };
  };
  return {
    async describe() {
      return {
        contractVersion: BLOCKER_CONTRACT_VERSION,
        product: ADGUARD_CLI_PRODUCT_LABEL,
        version: await probeVersion(input.binaryPath, input.logger),
        binarySha256: createHash("sha256").update(await readFile(input.binaryPath)).digest("hex"),
        kind: BlockerKind.Proxy,
        covers: COVERS,
        notReported: NOT_REPORTED,
        pageEvidence: {
          format: PageEvidenceFormat.AdguardMarkers,
          contentScriptHost: INJECTIONS_HOST
        }
      };
    },
    async start(request) {
      if (proxy !== null) {
        throw new Error("The AdGuard CLI blocker was started twice.");
      }
      const host = input.createProxy({
        binaryPath: input.binaryPath,
        workspaceDir: input.workspaceDir,
        logger: input.logger,
        filterLists: request.lists.map((list) => ({
          filterId: list.id,
          content: list.content
        }))
      });
      proxy = host;
      await host.prepare();
      await host.setEnabledFilters(request.enabledListIds);
      const started = running(await host.start());
      if (request.userRules.length === 0 && request.listReplacement === null) {
        return started;
      }
      const applied = await applyRequest(request);
      return { route: applied.route, revision: applied.revision };
    },
    apply: applyRequest,
    async state() {
      const snapshot = requireProxy("state").snapshot();
      const isRunning = snapshot.state === ProxyHostState.Running && snapshot.port !== null;
      const listIds = isRunning ? snapshot.executedFilterIds ?? [] : [];
      const lists = [];
      for (const id of listIds) {
        const bytes = await readFile(join3(input.workspaceDir, filterFilename(id)));
        lists.push({ id, sha256: createHash("sha256").update(bytes).digest("hex") });
      }
      const userRules = isRunning ? snapshot.executedUserRules ?? [] : [];
      return {
        running: isRunning,
        revision,
        port: isRunning ? snapshot.port : null,
        lists,
        userRules
      };
    },
    async log(cursor) {
      requireProxy("log");
      return await readAdguardCliLog(input.workspaceDir, cursor, revision);
    },
    async stop() {
      if (proxy === null) {
        return { licenceReleased: false };
      }
      await proxy.stop();
      route = null;
      return { licenceReleased: true };
    }
  };
}

// src/adguard-cli/adguard-cli-proxy.ts
import { createHash as createHash2, X509Certificate } from "node:crypto";
import { appendFile, mkdir as mkdir2, readFile as readFile2, rm as rm2, writeFile as writeFile2 } from "node:fs/promises";
import { promisify as promisify2 } from "node:util";
import { execFile as execFile2, spawn as spawn2 } from "node:child_process";
import { join as join4 } from "node:path";
var ADGUARD_CLI_PATH_ENV = "ADGUARD_CLI_PATH";
var ADGUARD_LICENSE_KEY_ENV = "ADGUARD_LICENSE_KEY";
var ADGUARD_CLI_HOME_PREFIX = "/tmp/agcli-";
var ADGUARD_CLI_HOME_ARCHIVE_ENV = "ADGUARD_CLI_HOME_ARCHIVE";
var SEEDED_DATA_DIR_FILENAME = ".agcli-data-dir";
var HOME_HASH_LENGTH = 12;
var ROOT_CERTIFICATE_NAME = "AdGuard Filters Agent";
var CERTIFICATE_EXTENSION = process.platform === "darwin" ? ".cer" : ".pem";
var COMMAND_TIMEOUT_MS = 6e4;
var SETUP_PORT = 0;
var DATA_DIRECTORY_LINE = /^Created data directory (.+)$/mu;
var VERSION_LINE2 = /^AdGuard CLI v(\S+)/mu;
var execFileAsync2 = promisify2(execFile2);
var REDACTED_LICENSE = "[redacted licence]";
function renderCliConfig(port, filterPaths, accessLogPath) {
  return [
    "proxy_mode: manual",
    "filtered_ports: 80:5221,5300:49151",
    "show_hints: false",
    "update_channel: default",
    "send_crash_reports: false",
    "log_level: info",
    "show_notifications: false",
    "listen_address: 127.0.0.1",
    "listen_ports:",
    `    http_proxy: ${port}`,
    "    socks5_proxy: -1",
    "listen_auth:",
    "    enabled: false",
    "    username: admin",
    "    password: admin",
    "worker_threads: 4",
    `access_log_file: ${JSON.stringify(accessLogPath)}`,
    "outbound_interface: null",
    "ad_blocking_enabled: true",
    "adguard_headers_enabled: false",
    "auto_enable_language_filters: false",
    // A bare `filters:` is YAML null, which the release rejects on every command, `activate`
    // and `reset-license` included; the setup configuration has no lists, so it says `[]`.
    ...filterPaths.length === 0 ? ["filters: []"] : ["filters:", ...filterPaths.map((path) => `    - ${JSON.stringify(path)}`)],
    "dns_filtering:",
    "    enabled: false",
    "    upstream: default",
    "    fallbacks: default",
    "    bootstraps: default",
    "    filters: []",
    "    block_ech: false",
    "    listen_port: -1",
    "https_filtering:",
    "    enabled: true",
    "    certificates_cache: .",
    `    root_certificate_name: ${ROOT_CERTIFICATE_NAME}`,
    "    filter_ev_certificates: false",
    "    enable_tls13: true",
    "    ocsp_check_enabled: false",
    "    enforce_certificate_transparency: false",
    "    http3_filtering_enabled: false",
    "    exclusions: https_exclusions.txt",
    "    filter_secure_dns_mode: off",
    "    encrypted_client_hello: false",
    "safebrowsing:",
    "    enabled: false",
    "    send_anonymous_statistics: false",
    "crlite:",
    "    enabled: false",
    "stealthmode:",
    "    enabled: false",
    "outbound_proxy:",
    "    enabled: false",
    "userscripts: []",
    "har_writer:",
    "    enabled: false",
    "    location: .",
    // An empty list crashes the release's config loader; it needs at least one entry.
    "apps:",
    "    - name: '*'",
    "      action: 'default'",
    ""
  ].join("\n");
}
function adguardCliHome(workspaceDir) {
  const digest = createHash2("sha256").update(workspaceDir).digest("hex");
  return `${ADGUARD_CLI_HOME_PREFIX}${digest.slice(0, HOME_HASH_LENGTH)}`;
}
function createAdguardCliProxyHost(input) {
  return createProxyHost(input, createAdguardCliEngine(input));
}
function createAdguardCliEngine(input) {
  const spawnProcess = input.spawnProcess ?? spawn2;
  const log = (fields, message) => {
    input.logger?.info(fields, `adguard cli ${message}`);
  };
  const home = adguardCliHome(input.workspaceDir);
  const outputLogPath = join4(input.workspaceDir, OUTPUT_LOG_FILENAME);
  const accessLogPath = join4(input.workspaceDir, ACCESS_LOG_FILENAME);
  const childEnv = { HOME: home, PATH: process.env.PATH, LANG: "en_US.UTF-8" };
  let dataDir = null;
  let activated = false;
  const requireDataDir = () => {
    if (dataDir === null) {
      throw new Error("The AdGuard CLI data directory is not known yet.");
    }
    return dataDir;
  };
  const runCommand = async (args, stdin = "") => {
    const chunks = [];
    const code = await new Promise((resolve) => {
      const spawned = spawnProcess(input.binaryPath, [...args], {
        env: childEnv,
        stdio: ["pipe", "pipe", "pipe"]
      });
      const timer = setTimeout(() => spawned.kill("SIGKILL"), COMMAND_TIMEOUT_MS);
      spawned.stdout?.on("data", (chunk) => chunks.push(chunk));
      spawned.stderr?.on("data", (chunk) => chunks.push(chunk));
      spawned.once("error", (error) => {
        clearTimeout(timer);
        chunks.push(Buffer.from(`spawn error: ${error.message}
`));
        resolve(null);
      });
      spawned.once("close", (exitCode) => {
        clearTimeout(timer);
        resolve(exitCode);
      });
      spawned.stdin?.end(stdin);
    });
    const output = Buffer.concat(chunks).toString("utf8").replaceAll(input.licenseKey, REDACTED_LICENSE);
    await appendFile(
      outputLogPath,
      `--- ${(/* @__PURE__ */ new Date()).toISOString()} adguard-cli ${args[0]} exited ${code}
${output}`,
      { mode: 384 }
    );
    return { code, output };
  };
  const writeConfiguration = async (port, filterFilenames) => {
    const config = renderCliConfig(
      port,
      filterFilenames.map((filename) => join4(input.workspaceDir, filename)),
      accessLogPath
    );
    await writeFile2(join4(requireDataDir(), CONFIG_FILENAME), config, { mode: 384 });
    await writeFile2(join4(input.workspaceDir, CONFIG_FILENAME), config, { mode: 384 });
  };
  const resetHome = async () => {
    await rm2(home, { recursive: true, force: true });
    await mkdir2(home, { recursive: true, mode: 448 });
  };
  const restoreSeededHome = async () => {
    await resetHome();
    try {
      await execFileAsync2("tar", ["-xzf", input.seededHomeArchive, "-C", home]);
      const relativeDataDir = (await readFile2(join4(home, SEEDED_DATA_DIR_FILENAME), "utf8")).trim();
      dataDir = join4(home, relativeDataDir);
    } catch (error) {
      log(describeError(error), "seeded home unusable, activating instead");
      return false;
    }
    await writeConfiguration(SETUP_PORT, []);
    const licence = await runCommand(["license"]);
    if (licence.code !== 0) {
      log(
        { exitCode: licence.code, output: licence.output },
        "seeded licence not active, activating instead"
      );
      return false;
    }
    log({ dataDir }, "licence restored from the seeded home");
    return true;
  };
  const activateFreshHome = async () => {
    await resetHome();
    dataDir = null;
    const version = await runCommand(["--version"]);
    const announced = DATA_DIRECTORY_LINE.exec(version.output);
    if (announced === null) {
      log({ exitCode: version.code, output: version.output }, "data directory unknown");
      throw new ProxyHostError(ProxyFailureCode.DataDirectoryUnknown);
    }
    dataDir = announced[1];
    log({ dataDir, version: VERSION_LINE2.exec(version.output)?.[1] ?? null }, "data directory");
    await writeConfiguration(SETUP_PORT, []);
    activated = true;
    const activation = await runCommand(["activate", input.licenseKey]);
    const licence = await runCommand(["license"]);
    if (licence.code !== 0) {
      log(
        {
          activateExitCode: activation.code,
          activateOutput: activation.output,
          licenseExitCode: licence.code,
          licenseOutput: licence.output
        },
        "activation failed"
      );
      throw new ProxyHostError(ProxyFailureCode.ActivationFailed);
    }
    log({ activateExitCode: activation.code }, "activated");
  };
  return {
    name: "adguard cli",
    async prepare() {
      if (!(input.seededHomeArchive !== void 0 && await restoreSeededHome())) {
        await activateFreshHome();
      }
      const generated = await runCommand(["cert"], "n\n");
      const certificatePath = join4(
        requireDataDir(),
        `${ROOT_CERTIFICATE_NAME}${CERTIFICATE_EXTENSION}`
      );
      try {
        const certificate = new X509Certificate(await readFile2(certificatePath));
        return {
          certificatePath,
          certificateDerBase64: certificate.raw.toString("base64")
        };
      } catch (error) {
        log(
          { exitCode: generated.code, output: generated.output, ...describeError(error) },
          "certificate unavailable"
        );
        throw new ProxyHostError(ProxyFailureCode.CertificateUnavailable, error);
      }
    },
    writeConfiguration,
    command() {
      return {
        args: ["start", "--no-fork", "--pid-file", join4(requireDataDir(), "adguard.pid")],
        env: childEnv
      };
    },
    async release() {
      if (activated) {
        activated = false;
        const reset = await runCommand(["reset-license"]);
        log(
          { exitCode: reset.code, output: reset.output },
          reset.code === 0 ? "licence reset" : "licence reset FAILED"
        );
      }
      await rm2(home, { recursive: true, force: true });
    }
  };
}

// src/adguard-cli/adguard-cli-module.ts
var ADGUARD_CLI_MODULE_ENV = [
  ADGUARD_CLI_PATH_ENV,
  ADGUARD_LICENSE_KEY_ENV
];
function unconfiguredBlocker(missing) {
  const refuse = async () => {
    throw new Error(`The AdGuard CLI module is not configured: set ${missing.join(" and ")}.`);
  };
  return {
    describe: refuse,
    start: refuse,
    apply: refuse,
    state: refuse,
    log: refuse,
    stop: async () => ({ licenceReleased: false })
  };
}
function startAdguardCliBlocker(environment, workspaceDir, logger) {
  const missing = ADGUARD_CLI_MODULE_ENV.filter((name) => !environment[name]);
  if (missing.length > 0) {
    return unconfiguredBlocker(missing);
  }
  const licenseKey = environment[ADGUARD_LICENSE_KEY_ENV];
  const seededHomeArchive = environment[ADGUARD_CLI_HOME_ARCHIVE_ENV] || void 0;
  return createAdguardCliBlocker({
    binaryPath: environment[ADGUARD_CLI_PATH_ENV],
    workspaceDir,
    logger,
    createProxy: (proxyInput) => createAdguardCliProxyHost({ ...proxyInput, licenseKey, seededHomeArchive })
  });
}

// src/adguard-cli/adguard-cli-module-main.ts
var INSTALLED_BINARY = join5("bin", "adguard-cli");
var stderrLogger = {
  info(fields, message) {
    process.stderr.write(`${JSON.stringify({ ...fields, msg: message })}
`);
  }
};
async function runAdguardCliModule() {
  const workspaceDir = process.env[BLOCKER_WORKSPACE_ENV];
  if (!workspaceDir) {
    throw new Error(`${BLOCKER_WORKSPACE_ENV} must name the module's private workspace.`);
  }
  const environment = {
    ...process.env,
    [ADGUARD_CLI_PATH_ENV]: process.env[ADGUARD_CLI_PATH_ENV] || join5(dirname(fileURLToPath(import.meta.url)), INSTALLED_BINARY)
  };
  await serveBlocker(
    startAdguardCliBlocker(environment, workspaceDir, stderrLogger),
    process.stdin,
    process.stdout
  );
}
function isEntryPoint() {
  const entry = process.argv[1];
  return entry !== void 0 && realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
}
if (isEntryPoint()) {
  await runAdguardCliModule();
}
export {
  runAdguardCliModule
};
