import { readFileSync } from 'node:fs';
import { GuidanceDocumentRole } from './guidance-source';
import type {
    KnowledgeGuidanceCitation,
    KnowledgeGuidanceSource,
    RuleGuidanceTopic,
} from './rule-guidance';

/**
 * One allowlisted document section used to answer a guidance topic.
 */
export interface GuidanceSection {
    /**
     * Trusted source document selector.
     */
    document: GuidanceDocumentRole;

    /**
     * Stable Markdown anchor used to locate the section.
     */
    anchor: string;

    /**
     * Heading text fallback for documents that omit an explicit anchor.
     */
    heading: string;
}

/**
 * One trusted document loaded for a fixed guidance section.
 */
export interface ResolvedGuidanceDocument {
    /**
     * Complete allowlisted Markdown document content.
     */
    content: string;

    /**
     * Immutable citation for the selected section.
     */
    citation: KnowledgeGuidanceCitation;
}

/**
 * Hard-coded routing from public topics to trusted document sections.
 */
export const GUIDANCE_SECTIONS: Record<RuleGuidanceTopic, readonly GuidanceSection[]> = {
    element_hiding: [
        {
            document: GuidanceDocumentRole.Syntax,
            anchor: 'cosmetic-elemhide-rules',
            heading: 'Element hiding rules',
        },
    ],
    css_injection: [
        {
            document: GuidanceDocumentRole.Syntax,
            anchor: 'cosmetic-css-rules',
            heading: 'CSS rules',
        },
    ],
    extended_css: [
        {
            document: GuidanceDocumentRole.Syntax,
            anchor: 'extended-css-selectors',
            heading: 'Extended CSS selectors',
        },
    ],
    network: [
        {
            document: GuidanceDocumentRole.Syntax,
            anchor: 'basic-rules-syntax',
            heading: 'Basic rule syntax',
        },
    ],
    scriptlet: [
        {
            document: GuidanceDocumentRole.Syntax,
            anchor: 'scriptlets',
            heading: 'Scriptlet rules',
        },
    ],
    exception: [
        {
            document: GuidanceDocumentRole.Syntax,
            anchor: 'exception-modifiers',
            heading: 'Exception rules modifiers',
        },
        {
            // The `#@#` contract — an exception cancels the rule carrying the same selector —
            // is documented inside the element-hiding section, not in a section of its own.
            document: GuidanceDocumentRole.Syntax,
            anchor: 'cosmetic-elemhide-rules',
            heading: 'Element hiding rules',
        },
    ],
    compatibility: [
        {
            document: GuidanceDocumentRole.Syntax,
            anchor: 'restrictions-and-limitations',
            heading: 'Restrictions and limitations',
        },
        {
            document: GuidanceDocumentRole.Syntax,
            anchor: 'compatibility-tables-legend',
            heading: 'Compatibility tables legend',
        },
    ],
    placement: [
        {
            document: GuidanceDocumentRole.Policy,
            anchor: 'common-criteria',
            heading: 'Common criteria',
        },
        {
            document: GuidanceDocumentRole.Contributing,
            anchor: 'rule-placement',
            heading: 'Rule placement',
        },
        {
            document: GuidanceDocumentRole.Contributing,
            anchor: 'repository-structure',
            heading: 'Repository structure',
        },
    ],
    policy: [
        {
            // The filter policy's acceptance criteria: what a rule must satisfy to be taken at
            // all. No new anchor is invented for this topic — the one section pinned here is
            // already resolved by `placement` at the pinned revision, and the startup check
            // refuses the whole session when any pinned heading has disappeared upstream.
            document: GuidanceDocumentRole.Policy,
            anchor: 'common-criteria',
            heading: 'Common criteria',
        },
    ],
};

/**
 * Convert a Markdown heading into the fallback anchor generated by Docusaurus/GitHub.
 *
 * @param heading - Heading text without Markdown prefix.
 * @returns Lowercase dash-separated anchor.
 */
function normalizeHeadingAnchor(heading: string): string {
    return heading
        .trim()
        .toLowerCase()
        .replace(/[`*_]/gu, '')
        .replace(/[^\p{L}\p{N}\s-]/gu, '')
        .replace(/\s+/gu, '-');
}

/**
 * Extract one complete Markdown section through the next same-or-higher-level heading.
 *
 * @param content - Trusted allowlisted Markdown document.
 * @param section - Section identifier selected by the fixed topic map.
 * @returns Complete section excerpt.
 */
export function extractSection(content: string, section: GuidanceSection): string {
    const lines = content.split(/\r?\n/u);
    const explicitAnchor = `{#${section.anchor}}`;
    const startIndex = lines.findIndex((line) => {
        const match = /^(#{1,6})\s+(.+?)\s*$/u.exec(line);
        if (!match) {
            return false;
        }
        const headingText = match[2].replace(/\s*\{#[^}]+\}\s*$/u, '');
        return (
            line.includes(explicitAnchor) ||
            headingText.trim().toLowerCase() === section.heading.toLowerCase() ||
            normalizeHeadingAnchor(headingText) === section.anchor
        );
    });
    if (startIndex < 0) {
        throw new Error(
            `Pinned guidance section ${section.anchor} was not found in its allowlisted document.`,
        );
    }
    const headingMatch = /^(#{1,6})\s+/u.exec(lines[startIndex]);
    const headingLevel = headingMatch?.[1].length ?? 6;
    let endIndex = lines.length;
    for (let index = startIndex + 1; index < lines.length; index += 1) {
        const nextHeading = /^(#{1,6})\s+/u.exec(lines[index]);
        if (nextHeading && nextHeading[1].length <= headingLevel) {
            endIndex = index;
            break;
        }
    }
    return lines.slice(startIndex, endIndex).join('\n').trim();
}

/**
 * Resolve one trusted path and immutable citation for an allowlisted section.
 *
 * @param source - Prepared immutable document source.
 * @param section - Fixed section selected from the topic map.
 * @returns File content and citation metadata.
 */
export function resolveDocument(
    source: KnowledgeGuidanceSource,
    section: GuidanceSection,
): ResolvedGuidanceDocument {
    if (section.document === GuidanceDocumentRole.Contributing) {
        const filePath = 'CONTRIBUTING.md';
        return {
            content: readFileSync(source.contributingPath, 'utf8'),
            citation: {
                repository: source.filtersRepository,
                commit: source.filtersCommit,
                filePath,
                anchor: section.anchor,
                url:
                    `https://github.com/${source.filtersRepository}/blob/` +
                    `${source.filtersCommit}/${filePath}#${section.anchor}`,
            },
        };
    }
    const filePath =
        section.document === GuidanceDocumentRole.Syntax
            ? 'docs/general/ad-filtering/create-own-filters.md'
            : 'docs/general/ad-filtering/filter-policy.md';
    const localPath =
        section.document === GuidanceDocumentRole.Syntax ? source.syntaxPath : source.policyPath;
    return {
        content: readFileSync(localPath, 'utf8'),
        citation: {
            repository: source.knowledgeBaseRepository,
            commit: source.knowledgeBaseCommit,
            filePath,
            anchor: section.anchor,
            url:
                `https://github.com/${source.knowledgeBaseRepository}/blob/` +
                `${source.knowledgeBaseCommit}/${filePath}#${section.anchor}`,
        },
    };
}
